#!/bin/bash
# ============================================
# Blue-Green Zero-Downtime Deploy Script
# ============================================
# Usage:
#   ./deploy.sh          — 일반 배포 (blue ↔ green 전환)
#   ./deploy.sh --init   — 최초 설치 (DB, Redis, Blue, Nginx 전부 시작)
#   ./deploy.sh --status — 현재 상태 확인
#
# 동작 방식:
#   1. 새 컬러 이미지 빌드 (기존 서비스 계속 운영)
#   2. 새 컬러 컨테이너 시작
#   3. 헬스체크 통과 대기
#   4. Nginx upstream을 새 컬러로 전환 (nginx -s reload)
#   5. 이전 컬러 컨테이너 정지 및 제거
#
# 다운타임: 0초 (Nginx reload는 기존 연결 유지)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

COMPOSE="docker compose"
STATE_FILE=".active-color"
HEALTH_TIMEOUT=120
HEALTH_INTERVAL=3

# ============================================
# Helpers
# ============================================

get_active() {
    [ -f "$STATE_FILE" ] && cat "$STATE_FILE" || echo ""
}

get_new_color() {
    [ "$(get_active)" = "blue" ] && echo "green" || echo "blue"
}

log() { echo "[$(date '+%H:%M:%S')] $*"; }

# Docker 헬스체크 상태로 판단
wait_healthy() {
    local container="dashboard-api-$1"
    local elapsed=0

    log "⏳ $container 헬스체크 대기..."
    while [ $elapsed -lt $HEALTH_TIMEOUT ]; do
        local status
        status=$(docker inspect --format='{{.State.Health.Status}}' "$container" 2>/dev/null || echo "not_found")

        case "$status" in
            healthy)
                log "✅ $container healthy!"
                return 0
                ;;
            unhealthy)
                log "❌ $container unhealthy!"
                return 1
                ;;
        esac

        sleep $HEALTH_INTERVAL
        elapsed=$((elapsed + HEALTH_INTERVAL))
        [ $((elapsed % 15)) -eq 0 ] && log "   ... $elapsed/$HEALTH_TIMEOUT s"
    done

    log "❌ $container 헬스체크 타임아웃 (${HEALTH_TIMEOUT}s)"
    return 1
}

# Nginx upstream 전환
switch_upstream() {
    local color=$1
    cat > nginx/upstream.conf << CONF
# Auto-generated by deploy.sh (active: $color)
# $(date '+%Y-%m-%d %H:%M:%S')

upstream api {
    server api-${color}:3000;
    keepalive 256;
    keepalive_requests 1000;
    keepalive_timeout 60s;
}

upstream dashboard {
    server dashboard-${color}:80;
}
CONF
    # Reload nginx if already running
    if docker ps --format '{{.Names}}' | grep -q 'dashboard-proxy'; then
        $COMPOSE exec -T nginx nginx -s reload
        log "🔄 Nginx reloaded → $color"
    else
        log "🔄 Nginx upstream config written → $color (nginx not yet running)"
    fi
}

# ============================================
# Commands
# ============================================

cmd_status() {
    local active=$(get_active)
    echo "======================================="
    echo "  Dashboard Blue-Green Status"
    echo "======================================="
    echo "  Active color : ${active:-none}"
    echo "  State file   : $STATE_FILE"
    echo ""
    echo "  Containers:"
    docker ps --format "  {{.Names}}\t{{.Status}}" --filter "name=dashboard-" 2>/dev/null || echo "  (none)"
    echo "======================================="
}

cmd_init() {
    log "======================================="
    log "  Initial Setup (Blue)"
    log "======================================="

    log ""
    log "📦 [1/5] Starting postgres, redis..."
    $COMPOSE up -d postgres redis

    log ""
    log "🔨 [2/5] Building blue images..."
    $COMPOSE --profile blue build

    log ""
    log "🚀 [3/5] Starting blue containers..."
    $COMPOSE --profile blue up -d

    log ""
    log "🏥 [4/5] Health check..."
    if ! wait_healthy "blue"; then
        log "❌ Init failed! Check logs: docker compose logs api-blue"
        exit 1
    fi

    log ""
    log "🌐 [5/5] Starting nginx..."
    switch_upstream "blue"
    $COMPOSE up -d nginx

    echo "blue" > "$STATE_FILE"

    log ""
    log "======================================="
    log "  ✅ Init complete! Active: blue"
    log "======================================="
}

cmd_deploy() {
    local cur=$(get_active)
    local new=$(get_new_color)

    if [ -z "$cur" ]; then
        log "No active deployment found. Running --init instead."
        cmd_init
        return
    fi

    log "======================================="
    log "  Blue-Green Deploy: $cur → $new"
    log "======================================="

    # 1. Build
    log ""
    log "🔨 [1/5] Building $new images..."
    $COMPOSE --profile "$new" build

    # 2. Start new
    log ""
    log "🚀 [2/5] Starting $new containers..."
    $COMPOSE --profile "$new" up -d

    # 3. Health check
    log ""
    log "🏥 [3/5] Health check..."
    if ! wait_healthy "$new"; then
        log "❌ Deploy failed! Rolling back..."
        docker stop "dashboard-api-$new" "dashboard-frontend-$new" 2>/dev/null || true
        docker rm -f "dashboard-api-$new" "dashboard-frontend-$new" 2>/dev/null || true
        log "  $cur is still active. No downtime occurred."
        exit 1
    fi

    # 4. Switch traffic
    log ""
    log "🔄 [4/5] Switching traffic → $new..."
    switch_upstream "$new"

    # 5. Stop old
    log ""
    log "🛑 [5/5] Stopping $cur containers..."
    docker stop "dashboard-api-$cur" "dashboard-frontend-$cur" 2>/dev/null || true
    docker rm -f "dashboard-api-$cur" "dashboard-frontend-$cur" 2>/dev/null || true

    echo "$new" > "$STATE_FILE"

    log ""
    log "======================================="
    log "  ✅ Deploy complete! Active: $new"
    log "======================================="
}

# ============================================
# Main
# ============================================

case "${1:-}" in
    --init)   cmd_init   ;;
    --status) cmd_status ;;
    --help|-h)
        echo "Usage: $0 [--init|--status|--help]"
        echo ""
        echo "  (no args)  Blue-Green 무중단 배포"
        echo "  --init     최초 설치 (postgres, redis, blue, nginx)"
        echo "  --status   현재 상태 확인"
        ;;
    *)        cmd_deploy ;;
esac
